name: Run build and tests on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-deploy:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get node version
        id: node
        run: |
          echo "::set-output name=version::$(node -v)"

      - name: Get node_modules cache
        uses: actions/cache@v4.0.2
        id: node_modules
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}-${{ steps.node.outputs.version }}
      - run: yarn install

      - name: Build Static Website
        env:
          VITE_AWS_REGION: ${{ vars.VITE_AWS_REGION }}
          VITE_AWS_USER_POOLS_ID: ${{ vars.VITE_AWS_USER_POOLS_ID }}
          VITE_AWS_USER_POOLS_WEB_CLIENT_ID: ${{ vars.VITE_AWS_USER_POOLS_WEB_CLIENT_ID }}
          VITE_GRAPH_QL_ENDPOINT: ${{ vars.VITE_GRAPH_QL_ENDPOINT }}
          VITE_TRANSLATIONS_FILE_URL: ${{ vars.VITE_TRANSLATIONS_FILE_URL }}
          VITE_SENTRY_DSN_URL: ${{ vars.VITE_SENTRY_DSN_URL }}
          VITE_ZENDESK_KEY: ${{ secrets.VITE_ZENDESK_KEY }}
        run: yarn run build

      - name: Run unit tests
        run: yarn run test
